apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mlops-2-0
  namespace: mlops-05
spec:
  selector:
    matchLabels:
      app: api-mlops-2-0
  replicas: 2
  template:
    metadata:
      labels:
        app: api-mlops-2-0
    spec:
      containers:
      - name: api-mlops-2-0
        image: ghcr.io/richardvanraes/mlops-2.0:sha-2584de8 # moet nog iets vinden op de sha-code automatisch te laten aanpassen
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  generateName: mlops-mypod-
  namespace: mlops-05
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: ghcr.io/richardvanraes/mlops-2.0:sha-2584de8
---
apiVersion: v1
kind: Service
metadata:
  name: api-mlops-service
  namespace: mlops-05
spec:
  selector:
    app: api-mlops-2-0
  ports:
  - nodePort: 30010
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort