name: MLOps Automation

on:
  push:
    branches: [ main, master ]

jobs:
  start:
    uses: ./.github/workflows/azure-ai.yml
    with:
      data_prep: true
      ai_training: true
      api_creation: true
      process_images: true
      split_images: true
      train_on_local: true
      local_deployment: true
    secrets: inherit
